#!/usr/bin/env bash
# Takes a file and copies it to remote server using scp and ssh
if [ $# -lt 3 ] ; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -i "$4" "$1" "$3"@"$2":~/
fi
