#!/usr/bin/env bash
# Install nginx on server and change default landing page
apt-get update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www
echo "Hello World!" > '/var/www/html/index.nginx-debian.html'
service nginx restart
