#!/usr/bin/env bash
# Install nginx on server and change default landing page
apt-get update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www
echo "Hello World!" > '/var/www/html/index.nginx-debian.html'
service nginx restart
redirect="	location = /redirect_me {\n		rewrite ^/replace_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n	}"
match="	server_*"
sed -i "/$match/a $redirect" /etc/nginx/sites-available/default
sudo nginx -s reload
